config/routes.rb
Rails.application.routes.draw do
  resources :cart_items do 
    get '/remove_from_cart', to: 'cart_items#remove_from_cart', as: 'remove_from_cart'
  end
  resources :carts do 
    get 'checkout'
  end
  resources :restaurants
  resources :menus do
    get '/:cart_id/add_to_cart', to: 'menus#add_to_cart', as: 'add_to_cart'
  end
  resources :home
  root 'home#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'newrest', to: 'restaurants#new', as: 'newrest'
  get 'newmenu', to: 'menus#new', as: 'newmenu'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index        
    unless current_user.nil?
      cart_items = CartItem.joins("INNER JOIN carts on carts.id = cart_items.cart_id AND carts.active = 't'").where(user_id:current_user.id).first
      @history = Cart.select("carts.id as id, restaurants.name as name, date(carts.created_at) as created_at, sum(menus.price) as total_price, carts.active as status")
      .joins("INNER JOIN cart_items on cart_items.cart_id=carts.id")
      .joins("INNER JOIN menus on menus.id=cart_items.menu_id")
      .joins("INNER JOIN restaurants on restaurants.id=menus.restaurant_id").where(user_id: current_user.id).group("carts.id")
      if cart_items != nil 
        puts cart_items.cart_id
        @carts = Cart.where(id:cart_items.cart_id, active: true).first        
      else
        @carts = Cart.where(user_id:current_user.id, active: true).first
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div>
  <% if current_user %>
  <%= react_component 'Main', { currentUser: current_user } %>
  <p>Logged in as <%= current_user.email %>.</p>
  <p>Current user_id <%= current_user.id %>.</p>
  <% unless @carts.nil? %>
    <% if @carts.active == true %>
      <p><%= link_to "View Cart", @carts %></p>  
    <% else %>
      <%= link_to 'New Group Cart', new_cart_path %>
    <% end %>
  <% else %>
    <%= link_to 'New Group Cart', new_cart_path %>
  <% end %>
  <p><%= link_to "Log Out", logout_path %></p>  
  <% else %>
    <%= link_to "Sign Up", signup_path %> or 
    <%= link_to "Log In", login_path %>
  <% end %>  
  <hr />
  <p>
  <h2>
  <strong> History</strong>
  </h2>
  <table>
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Restaurant</th>
        <th>Order Date</th>
        <th>Total Price</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% unless @history.nil? %>
        <% @history.each do |menu| %>
          <tr>
            <td><%= menu.id %></td>
            <td><%= link_to menu.name, menu %></td>
            <td><%= menu.created_at %></td>
            <td><%= menu.total_price %></td>
            <td><%= menu.status %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
  </table>
</div>