config/routes.rb
Rails.application.routes.draw do
  resources :cart_items do 
    get '/remove_from_cart', to: 'cart_items#remove_from_cart', as: 'remove_from_cart'
  end
  resources :carts do 
    get 'checkout'
  end
  resources :restaurants
  resources :menus do
    get '/:cart_id/add_to_cart', to: 'menus#add_to_cart', as: 'add_to_cart'
  end
  resources :home
  root 'home#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'newrest', to: 'restaurants#new', as: 'newrest'
  get 'newmenu', to: 'menus#new', as: 'newmenu'
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_item
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    id = params[:id]
    @cart_items = CartItem.where(cart_id:id)
    if @cart_items.length > 0 
      @restaurants = Restaurant.where(id: @cart_items.first.menu.restaurant.id)
    else
      @restaurants = Restaurant.all
    end

    @user = User.where(id: @cart.user_id).first
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
    @is_edit = true
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    @cart.active = true
    @cart.user_id = current_user.id
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end 
  
  def checkout
    id = params[:cart_id]
    respond_to do |format|
      cart = Cart.find_by(id: id)
      cart.active = false
      if cart.save 
        format.html { redirect_to '/', notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: '/' }
      else
        puts 'wiw'
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:name, :active, :max, :user_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cart_name %>
  </div>

  <% if @is_edit %>
    <div class="field">
      <%= form.label :active %>
      <%= form.check_box :active, id: :cart_active %>
  </div>
  <% end %>

  <% if false %>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :cart_user %>
  </div>
  <% end %>

  <div class="field">
    <%= form.label :max %>
    <%= form.number_field :max, id: :max_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.name %></td>
        <td><%= cart.active %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', home_index_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cart.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @cart.active %>
</p>

<p>
  <strong>Max Price:</strong>
  <%= @cart.max %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @user.email %>
</p>

<p>
<hr />
<p>
  <strong>Your Cart:</strong>
</p>
<table>
  <thead>
    <tr>
      <th>Menu</th>
      <th>Price</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @cart_items.each do |item| %>
      <tr>
        <td><%= item.menu.name %></td>        
        <td><%= item.menu.price %></td>
        <td><%= item.user.email %></td>
        <% if current_user.id == @cart.user_id || item.user.id == current_user.id %>
          <td><%= link_to 'Remove', cart_item_remove_from_cart_url(item.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>  
</p>
<hr />
<p>
<table>
  <thead>
    <tr>
      <th>List of Restaurants</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>                
      </tr>
    <% end %>
  </tbody>
</table>  
</p>

<% if current_user.id == @cart.user_id %>
<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Checkout', cart_checkout_url(@cart.id) %> |
<% end %>
<%= link_to 'Back', home_index_path %>