config/routes.rb
Rails.application.routes.draw do
  resources :cart_items do 
    get '/remove_from_cart', to: 'cart_items#remove_from_cart', as: 'remove_from_cart'
  end
  resources :carts do 
    get 'checkout'
  end
  resources :restaurants
  resources :menus do
    get '/:cart_id/add_to_cart', to: 'menus#add_to_cart', as: 'add_to_cart'
  end
  resources :home
  root 'home#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'newrest', to: 'restaurants#new', as: 'newrest'
  get 'newmenu', to: 'menus#new', as: 'newmenu'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :menu
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    id = params[:id]
    @menus = Menu.where(restaurant:id)
    @cart = Cart.where(active: true).first
    @cart_item = CartItem.new
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :has_many)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Has many</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  <%= link_to 'New Restaurant', new_restaurant_path %>
  <br>
  <%= link_to 'Home', home_index_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant's Name:</strong>
  <%= @restaurant.name %>
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price ($) </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %> 
      <tr>
        <td><%= menu.name %></td>        
        <td><%= menu.price %></td>
        <td><%= link_to 'Add to Cart', menu_add_to_cart_url(menu.id, @cart.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', home_index_path %>